services:
  # MariaDB Database
  - type: pserv
    name: churn-database
    env: image

    image:
      url: mariadb:11

    envVars:
      - key: MARIADB_ROOT_PASSWORD
        value: root123
      - key: MARIADB_DATABASE
        value: churn_db
      - key: MARIADB_USER
        value: vivek
      - key: MARIADB_PASSWORD
        value: password123

    disk:
      name: mariadb-data
      mountPath: /var/lib/mysql
      sizeGB: 1